include common.mk

all: elfs

#	-ffunction-sections \
#	-fdata-sections \


#	-fno-stack-protector \

COPTS += -m68000 \
	 -mstrict-align \
	 -D R_68K_RELATIVE=22

#	-I_build/headers/include

# stop deleting my dbg elf!
.SECONDARY:

#%.elf.dbg: %.pie.o
#	$(BFDLD) \
#		--gc-sections \
#		--print-gc-sections \
#		--no-dynamic-linker \
#		--hash-style=gnu \
#		--undefined=_start_c \
#		-pie $^ -o $@


#	-Wl,--no-dynamic-linker \

STATICPIE=-fpie -pie -Wl,--no-dynamic-linker

# This reduces the size of the binaries by putting segments
# with different permissions on the same 4K page which you
# might care about if you have an MMU.
COPTS += -Wl,-z,max-page-size=4

%.68000.elf.dbg: %.c $(HEADERS) libgcc_68000.a
	$(MSG) CC $*
	$(Q)$(CC) $(COPTS) \
	$(STATICPIE) \
	-o $@ $< libgcc_68000.a

%.68000.elf: %.68000.elf.dbg
	$(MSG) STRIP $*
	$(Q)$(STRIP) $< -o $@

.PHONY: system_elfs user_elfs
SYSTEM_ELFS = $(addsuffix .68000.elf,$(PROGS_SYSTEM))
SYSTEM_ELFS += $(addsuffix .68000.elf,$(PROGS_NET_SYSTEM))
USER_ELFS = $(addsuffix .68000.elf,$(PROGS_USER))
USER_ELFS += $(addsuffix .68000.elf,$(PROGS_NET_USER))

elfs: $(SYSTEM_ELFS) $(USER_ELFS)

.PHONY: m68k.tar
m68k.tar: rootfs.tarwak.json elfs
	$(MSG) TARWAK $@
	$(Q)$(TARWAK) -i rootfs.tarwak.json -o $@ -b ./ -p "%s.68000.elf" $(_TARWAKFEATURES)

.PHONY: m68k.erofs
m68k.erofs: m68k.tar
	$(MSG) EROFS $@
	$(Q)$(EROFS_CMD) $@ $<

.PHONY: clean
clean:
	$(Q)rm -f *.o *.gdb *.68000.elf *.68000.elf.dbg m68k.tar m68k.erofs
