include common.mk

all: elfs

#	-ffunction-sections \
#	-fdata-sections \


COPTS += -m68000 \
	 -D R_68K_RELATIVE=22

#	-I_build/headers/include

# stop deleting my dbg elf!
.SECONDARY:

#%.elf.dbg: %.pie.o
#	$(BFDLD) \
#		--gc-sections \
#		--print-gc-sections \
#		--no-dynamic-linker \
#		--hash-style=gnu \
#		--undefined=_start_c \
#		-pie $^ -o $@


#	-Wl,--no-dynamic-linker \

STATICPIE=-fpie -pie -Wl,--no-dynamic-linker

# This reduces the size of the binaries by putting segments
# with different permissions on the same 4K page which you
# might care about if you have an MMU.
COPTS += -Wl,-z,max-page-size=4

%.68000.elf.dbg: %.c common.h
	$(CC) $(COPTS) \
	$(STATICPIE) \
	-o $@ $< -lgcc

%.68000.elf: %.68000.elf.dbg
	$(STRIP) $< -o $@

.PHONY: elfs
elfs: $(addsuffix .68000.elf,$(PROGS))

.PHONY: clean
clean:
	rm -f *.o *.gdb *.68000.elf *.68000.elf.dbg

.PHONY: m68k.erofs
m68k.erofs: elfs
	mkdir -p m68kroot/sys
	mkdir -p m68kroot/dev
	mkdir -p m68kroot/proc
	mkdir -p m68kroot/tmp
	mkdir -p m68kroot/bin
	mkdir -p m68kroot/sbin

	cp init.68000.elf m68kroot/sbin/init
	cp getty.68000.elf m68kroot/sbin/getty

	cp smolsh.68000.elf m68kroot/bin/smolsh
	cp ls.68000.elf m68kroot/bin/ls
	cp ps.68000.elf m68kroot/bin/ps
	cp dmesg.68000.elf m68kroot/bin/dmesg
	cp cat.68000.elf m68kroot/bin/cat
	cp mkdir.68000.elf m68kroot/bin/mkdir
	cp xxd.68000.elf m68kroot/bin/xxd
	cp man.68000.elf m68kroot/bin/man
	cp sha256sum.68000.elf m68kroot/bin/sha256sum
	cp uname.68000.elf m68kroot/bin/uname
	cp cp.68000.elf m68kroot/bin/cp
	cp mv.68000.elf m68kroot/bin/mv
	cp ln.68000.elf m68kroot/bin/ln
	cp touch.68000.elf m68kroot/bin/touch

	mkfs.erofs -zlz4 $@ m68kroot/
