_build:
	mkdir $@

NOLIBCBRANCH=nolibc-staticpie-20260829
NOLIBCREPO=https://github.com/fifteenhex/linux.git

TOOLCHAIN_URL="https://www.kernel.org/pub/tools/crosstool/files/bin/x86_64/15.2.0"
TOOLCHAIN_M68K=x86_64-gcc-15.2.0-nolibc-m68k-linux.tar.xz
TOOLCHAIN_DIR=gcc-15.2.0-nolibc
#TOOLCHAIN_URL="https://www.kernel.org/pub/tools/crosstool/files/bin/x86_64/14.3.0/"
#TOOLCHAIN_M68K=x86_64-gcc-14.3.0-nolibc-m68k-linux.tar.xz
#TOOLCHAIN_DIR=gcc-14.3.0-nolibc

TOOLCHAIN_X86_64=x86_64-gcc-15.2.0-nolibc-x86_64-linux.tar.gz

_build/.stamp.linux_cloned: | _build
	git -C _build clone --depth 1 --branch $(NOLIBCBRANCH) \
		--filter=blob:none --sparse $(NOLIBCREPO)
	git -C _build/linux sparse-checkout set tools/include/nolibc
	touch $@

TARWAKBRANCH=master
TARWAKREPO=https://github.com/fifteenhex/tarwak.git

_build/.stamp.tarwak_cloned: | _build
	git -C _build clone --depth 1 --branch $(TARWAKBRANCH) $(TARWAKREPO)
	touch $@

define toolchain_targets
_build/$(TOOLCHAIN_$(1)): | _build
	wget $(TOOLCHAIN_URL)/$(TOOLCHAIN_$(1)) -O $$@

_build/.stamp.toolchain_$(2)_extracted: _build/$(TOOLCHAIN_$(1))
	tar -C _build/ -xaf _build/$(TOOLCHAIN_$(1))
	touch $$@

TOOLCHAINDEP += _build/.stamp.toolchain_$(2)_extracted
endef

$(eval $(call toolchain_targets,M68K,m68k))
$(eval $(call toolchain_targets,X86_64,x86_64))

UAPI_M68K = /usr/m68k-linux-gnu/include
UAPI_X86_64 = /usr/include /usr/include/x86_64-linux-gnu

NOLIBCPATH = `realpath _build/linux/tools/include/nolibc/`

TARWAK=_build/tarwak/build/tarwak
$(TARWAK): _build/.stamp.tarwak_cloned
	cd _build/tarwak && meson setup build
	cd _build/tarwak/build && meson compile

SIXEIGHTOPTS = UAPIDIR="$(UAPI_M68K)" \
		NOLIBCDIR=$(NOLIBCPATH) \
		CROSS_COMPILE=`realpath _build/$(TOOLCHAIN_DIR)/m68k-linux/bin/m68k-linux-` \
		TARWAK=`realpath $(TARWAK)`


PEKEHACHIROKUOPTS = UAPIDIR="$(UAPI_X86_64)" \
		NOLIBCDIR=$(NOLIBCPATH) \
		CROSS_COMPILE=`realpath _build/$(TOOLCHAIN_DIR)/x86_64-linux/bin/x86_64-linux-` \
		TARWAK=`realpath $(TARWAK)`

# Let clang-tidy work without all the other jank
TIDYOPTS = UAPIDIR="$(UAPI_X86_64)" \
		NOLIBCDIR=$(NOLIBCPATH) \
		CROSS_COMPILE=none \
		TARWAK=none

.PHONY: clang-tidy
clang-tidy: _build/.stamp.linux_cloned
	$(MAKE) -f Makefile.x86_64 $(TIDYOPTS) clang-tidy

.PHONY: build
build: $(TOOLCHAINDEP) _build/.stamp.linux_cloned $(TARWAK)
	$(MAKE) -f Makefile.68000 $(SIXEIGHTOPTS) m68k.erofs
	$(MAKE) -f Makefile.x86_64 $(PEKEHACHIROKUOPTS) x86_64.erofs

BOOT_TIMEOUT ?= 30

# By default use whatever the newest installed kernel is
KERNEL ?= $(shell ls -1 /boot/vmlinuz-* 2>/dev/null | sort -V | tail -1)

.PHONY: boot

QEMUNET = -netdev user,id=net0 -device e1000,netdev=net0

QEMUCMD = qemu-system-x86_64 -nographic -no-reboot -m 128 -kernel $$kernel -initrd $$initrd \
	$(QEMUNET) \
	-append "console=ttyS0 quiet -- smolinit.getty=/dev/ttyS0 smolinit.hostname=eighty6 smolinit.dhcpif=eth0 smolinit.telnetd=23 $$insmod"

BOOT_MODULE = e1000

boot: $(TOOLCHAINDEP) _build/.stamp.linux_cloned $(TARWAK)
	$(MAKE) -f Makefile.x86_64 $(PEKEHACHIROKUOPTS) x86_64.cpio.gz
	kernel="$(KERNEL)"; \
	if [ ! -r "$$kernel" ]; then \
		echo "can't read a kernel to boot: $${kernel:-none found}"; exit 1; \
	fi; \
	initrd=x86_64.cpio.gz; insmod=; \
	module=`find /lib/modules/$${kernel##*/vmlinuz-} -name '$(BOOT_MODULE).ko*' 2>/dev/null | head -1`; \
	if [ -n "$$module" ]; then \
		echo "packing $$module"; \
		rm -rf _build/modules; \
		mkdir -p _build/modules/lib/modules; \
		cp $$module _build/modules/lib/modules/; \
		( cd _build/modules && bsdtar --format=newc --uid 0 --gid 0 -cf - lib ) \
			| gzip -9 > modules.cpio.gz; \
		cat x86_64.cpio.gz modules.cpio.gz > boot.cpio.gz; \
		initrd=boot.cpio.gz; \
		insmod="smolinit.insmod=/lib/modules/`basename $$module`"; \
	else \
		echo "no $(BOOT_MODULE) module for this kernel, booting without a network"; \
	fi; \
	echo "booting with $$kernel"; \
	timeout --foreground $(BOOT_TIMEOUT) $(QEMUCMD); \
	ret=$$?; \
	if [ $$ret -eq 124 ]; then \
		echo "still running after $(BOOT_TIMEOUT)s"; \
	else \
		echo "qemu exited with $$ret"; exit $$ret; \
	fi

.PHONY: clean
clean:
	$(MAKE) -f Makefile.68000 $(SIXEIGHTOPTS) clean
	$(MAKE) -f Makefile.x86_64 $(PEKEHACHIROKUOPTS) clean
	rm -rf modules.cpio.gz boot.cpio.gz _build/modules
